<a href="https://colab.research.google.com/github/AshrithSagar/CP220-M4RAS-2024/blob/main/3_hw_cp220_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Lab 3**

*Topics*

Gaussian Elimination <br>
Inverse & Non-Singular <br>
LU Factorization <br>
Least Squares <br>
Number representation <br>
Orthogonality, Gram-schmidt, Householder <br>
Projection Matrices <br>





---
**Q1**

Let $A=\begin{bmatrix} a_{:1} & a_{:2} & .. & a_{:n} \end {bmatrix}$ be a $mxn$ matrix and $B = \begin{bmatrix} b_{:1}^T \\ b_{:2}^T \\ .. \\ b_{:n}^T \end{bmatrix}$ be a $nxk$ matrix.

Express $AB$ in terms of the products of columns of A and rows of B. What is its dimensions





Ans:

$AB = \sum_{i=1}^n a_{:i}b_{:i}^T$ and is a $mxk$ matrix

In order to see this, let $A:U_n → V_m$ and $B: W_k → V_m$

Then $AB: W_k → V_m$

Let $w \in W_k$ and $w = \begin{bmatrix} w_1 \\ w_2 \\ .. \\w_k \end{bmatrix}$

$Bw = \begin{bmatrix} b_{:1}^T w \\ b_{:2}^T w \\ .. \\ b_{:n}^T w \end{bmatrix}$

Therefore $ABw = A\begin{bmatrix} b_{:1}^T w \\ b_{:2}^T w \\ .. \\ b_{:n}^T w \end{bmatrix} = (b_{:1}^T w) a_{:1} + (b_{:2}^T w)a_{:2} + .. + (b_{:n}^T w) a_{:n}$

In the right side - we are adding scalar multiples of all columns of A. Note that for any scalar $\lambda$, $\lambda \begin{bmatrix} a_1 \\ a_2 \\ ... \\ a_m \end{bmatrix} = \begin{bmatrix} a_1 \\ a_2 \\ ... \\ a_m \end{bmatrix} \lambda$

Hence we can rewrite
$ABw = a_{:1} (b_{:1}^T w) + a_{:2} (b_{:2}^T w) + ... = (a_{:1}b_{:1}^T) w + (a_{:2}b_{:2}^T)w + ... $ by associativity

Hence the results follows.

---

**Review of Gaussian elmination**

Given the matrix equation $Ax = b$ with unknown vector $x$ that needs to be determined,

Gaussian elimination method proceeds by systematically multiplying the equation on the left side by elementary row matrices - which are lower triangular with all diagonals '1' leading to $A$ becoming upper triangular.

$E_1 Ax =  E_1b$

$E_2 E_1 Ax = E_2 b$

...

$E_r E_{r-1} ... E_1 A x = E_r E_{r-1} ... E_1 b$


The $E_i$ are chosen from the matrix in the previous step (we will call it $A_{i-1}$ by taking $A_{i-1}[ii]$ as the pivot element, and dividing the ith row by it and scaling and substracting from all rows below it to give 0s in the column below this element. In case this element is itself 0, we can look along the row for the first non-zero element (or the largest non-zero element), swap the two columns and proceed. Note that swapping  columns is equivalent to post-multiplication A by the appropriate permutation matrix.

We have seen that the product of lower triangular matrices remains lower triangular and hence $E = E_r E_{r-1} ... E_1 $ is a lower triangular matrix.

$EAx = Ux = b$ where $U$ is a upper triangular matrix. We can solve the latter by back substitution.

---

**Inverse of a square matrix**

Let $A$ be a square $(nxn)$ matrix. Then if there exists a matrix represented as $A^{-1}$ such that

$A^{-1} A = A A^{-1} = I $, the identity matrix, then $A^{-1}$ is the inverse of $A$

A is than called a *Non-Singular* matrix. Every full-rank square matrix is non-singular.


Note that if $B$ is the left inverse of $A$, i.e. $BA = I$  and $C$ is the right inverse of $A$, i.e $AC = I$ then $B=C=A^{-1}$

$BI = B => B(AC) = B => (BA)C = B => IC = C = B$

We can see that:

$(AB)^{-1} = B^{-1}A^{-1}$

Similarly: $(ABC)^{-1} = C^{-1}B^{-1}A^{-1}$ and so on.


---
**Finding inverse via Gaussian Elimination**

We need to find $B$ such that $AB = I$, i.e. $A\begin{bmatrix} b_{:1} & b_{:2} & ... & b_{:n} \end{bmatrix} = \begin{bmatrix} 1 & 0 & 0& ... & 0 \\ 0 & 1 & 0 & ... & 0 \\ ... \\ 0 & 0 & 0 & ... & 1 \end{bmatrix}$

So we need to solve $n simultaneous equations:

$A b_{:1} = e_1$

$A b_{:2} = e_2$

...

$Ab_{:n} = e_n$

By the Gaussian elimination procedure, we can find a lower triangular matrix $E$ such that $EA = U$ an upper triangular matrix.

So we can do $EAB = UB = EI$ and we can solve for each unknown column of $B$ by back substitution

---
**Inverse of a lower triangular matrix with diagonal 1s**

Let $L = \begin{bmatrix} 1 & 0 & 0 & ... & 0 \\ l_{21} & 1 & 0 & ... & 0 \\ l_{31} & l_{32} & 1 & ... & 0 \\ ... \\ l_{n1} & l_{n2} & l_{n3} & ... & 1 \end{bmatrix}$ be a lower triangular matrix with non-zero diagonal entries


Find an $E$ such that $EL = I$

If we apply Gaussian elimination process, we get

$E_1  = \begin{bmatrix} 1 & 0 & 0 & ... & 0 \\ -l_{21} & 1 & 0 & ... & 0 \\ -l_{31} & 0 & 1 &  ... & 0 \\ ... \\ -l_{n1} & 0 & 0 & ... & 1 \end{bmatrix}$

and so on to give $EL = U=I$ on left side and $EI = E$ on right side. Therefore $E = L^{-1} = \begin{bmatrix} 1 & 0 & .. & 0 \\ -l_{21} & 1 & .. & 0 \\ ... \\ -l_{n1} & -l_{n2} & .. & 1 \end{bmatrix} $



---
**LU Factorization**

Therefore.  $EAx = Ux = Eb = L^{-1}b$

In other words. $EA = L^{-1}A = U => A = LU$

Thus we have factorized a square matrix $A$ via Gaussian Elimination into a product of lower triangular and upper triangular matrix.

While $L$ has 1s in the diagonal, the upper triangular matrix $U$ might not have. We can pull out the diagonals and write

$A = LDU$ where L, U are lower and upper triangular with 1s in the diagonal and D is a diagonal matrix.

Note that we can factorize $D=D_1 D_2$ in arbitary ways and hence $A= (LD_1)(D_2U)$ leads to infinitely many LU factorizations $LD_1$ is lower triangular and $D_2U$ is upper triangular.



---
However if $A=LDU$ and $L$ and $U$ are lower and upper triangular respectively with  ones in the diagonal, and if $A$ is invertible, the factorization is unique.

If $A$ is invertible, so are $L, D, U$.

Let $A = L_1 D_1 U_1 = L_2 D_2 U_2$ be two possible factorizations.

Then $D_1U_1U_2^{-1} = L_1^{-1}L_2D_2$.

Note that $U_2^{-1}$ is upper triangular and $L_1^{-1}$ is lower triangular. So in the above equation, lower triangular is equal to upper triangular which can only happen if off-diagonal entries are 0 and diagonal entries are same i.e. $D_1 = D_2$

This also means that $L_1^{-1}L_2 = I$ which means $L_1 = L_2$. Similarly $U_1 = U_2$

Thus if $A$ invertible, there is a unique $LDU$ factorization with $L,U$ lower and upper triangular with diagonals 1.





---
**Number of multiplications for find LU factorization**

$O(n^3)$

If we want to use same matrix $A$ repeatedly to solve for different $b$ in $Ax=b$, then we can factorize $A=LU$ and then do

$Ly = b$ as forward calculation and $Ux = y$ via back substitition to get $x$.

This has $O(n^2)$ multiplications



**Row Echelon Form & Pivots **

The structure of $U$ after gaussian elimination tells us which are the linearly independent columns. It has a echelon form (step form) as the boundary between non-zero and zero entries

---
**A Brief on Computing Architecture**

The computing machine has some arithmetic and logic units (ALU) which are connected to memories. The most significant component of the ALU is the Multiply Accumulate Unit (MAC) which is does a multiply and addition. This is important for matrix-vector multiply (or dot product) :

$ s = \sum_{i=1}^n a_i b_i$ is realized as

```python
s=0
for i in range(n):
   s = s + a[i] b[i] #Multiply accumulate
```
GPU and CPU optimize hardware to speedup this operation - and can be taken advantage of by using vectorized machine instructions. This low level implementation detail is usually hidden in libraries and is exposed as high level API (application programming interfaces).

Usually the numbers are floating point (to approximate better the real numbers) and hence the speed is measured in Floating Point Operations per Second (FLOPS)
For example, the V100 GPU from Nvidia can do 15.7 Tera FLOPS of single precision arithmetic.

Memory is the other important piece here. The data needs to be stored here and it needs to be streamed out to be fed into the MAC units (or execution cores). Memory within the same integrated circuit of GPU or CPU, allows for rapid streaming out and in of operands and results respectively. There is memory outside the CPU/GPU cores - in main memory (DRAMs), which are slower to slurp in from.

---
**numpy**

is a numerical matrix computation  library in *python*

There are many such libraries in other programming languages.

We will use the popular numerical linear algebra package numpy
https://numpy.org/doc/stable/user/index.html
The above website has documentation, tutorials etc.


In [ ]:
#import the package for numerical linear algebra computations in Python
import numpy as np

---
**Execution speed comparison of vectorised and non-vectorised code**
We will generate a random vector with N entries and then use the timeit function to measure its execution time for two different implementations. A naive one using for loops and a vectorized one.

*%%timeit -n num_loops -r num_runs*
at the top of a cell, instruments it to measure execution time of the cell.

The content of a cell are run back-to-back *num_loops* times each run and the execution time is measured. Thus the execution time of the code in the cell, measured for a single run:  $\frac{execution\_time}{num\_loops}$.

This repeated *num_run* times to collect execution times across different runs and then averaged and std_dev is obtained.



In [ ]:

N=10000
x = np.random.rand(N,1)

In [ ]:
#find average
%%timeit -n 100 -r 30
sum = 0
for i in range(len(x)):
  sum = sum + x[i,0]

avg = sum/N

1.94 ms ± 490 µs per loop (mean ± std. dev. of 30 runs, 100 loops each)


In [ ]:
%%timeit -n 100 -r 30
avg = np.ones(N) @ x / N

11.5 µs ± 4.29 µs per loop (mean ± std. dev. of 30 runs, 100 loops each)


In [ ]:
#alternative using np.sum
%%timeit -n 100 -r 30
avg = np.sum(x)/N

9.31 µs ± 2.73 µs per loop (mean ± std. dev. of 30 runs, 100 loops each)


In [ ]:
#find std deviation
%%timeit -n 100 -r 30
sum = 0
for i in range(len(x)):
  sum = sum + (x[i,0]-avg)**2

std_dev = np.sqrt(sum/N)


25.3 ms ± 5.15 ms per loop (mean ± std. dev. of 30 runs, 100 loops each)


---
**Q2: Vectorized implementation for calculating std dev**

In [ ]:
%%timeit -n 100 -r 30
avg = np.sum(x)/N
#std_dev = <your code here>
std_dev = np.sqrt(((x-avg).T @ (x-avg))/N)

21.1 µs ± 6.29 µs per loop (mean ± std. dev. of 30 runs, 100 loops each)


---
**Q3**

Find the a) rank of A and b) the basis vectors of its null space, given that:

$A = L U = \begin{bmatrix} 1 & 0 & 0 & 0 \\ 3 & 1 & 0 & 0 \\ 4 & 1 & 3 & 0 \\ 6 & 4 & 3 & 2 \end{bmatrix} \begin{bmatrix} 1 & 3 & 0 & 1 & 2 & 1 \\ 0 & 0 & 3 & 4 & 0 & 0 \\ 0 & 0 & 0 & 0 & 0 & 3\\ 0 & 0 & 0 & 0 & 0 & 0 \end{bmatrix}$


Ans:

$rank(A) = rank(L)rank(U)$. $rank(L)=4$ as it is lower triangular with all non-zero diagonal. $rank(U) = 3$ has it has 3 non-zero pivots. The linearly independant columns of $U$ are $1, 3, 6$.

By taking a sub-matrix of columns $U^{'}=\begin{bmatrix}U_{:1}& U_{:3} & U_{:6} \end{bmatrix}$ and then finding the solutions $v_1, v_2 \& v_3$ such that $U^{'}v_1=U_{:2}$,  $U^{'}v_2=U_{:4}$ $U^{'}v_3=U_{:5}$

allows us to construct the basis vectors

$b_1=\begin{bmatrix}v_1[1] & -1 & v_1[2] & 0 & 0 & v_1[6]\end{bmatrix}^T$

$b_2=\begin{bmatrix}v_2[1] & 0 & v_2[2] & -1 & 0 & v_2[6]\end{bmatrix}^T$

$b_3=\begin{bmatrix}v_3[1] & 0 & v_3[2] & 0 & -1 & v_3[6]\end{bmatrix}^T$

Hence one basis of the null space is $\{ \begin{bmatrix} 3 & -1 & 0 & 0 & 0 & 0\end{bmatrix}^T, \begin{bmatrix} 1 & 0 & 4/3 & -1 & 0 & 0 \end{bmatrix}^T,\begin{bmatrix} 2 & 0 & 0 & 0 & -1 & 0 \end{bmatrix}^T\}$

---
**Q4**
Find all 2x2 matrices $A$ such that $A^2=I$

Ans:

Let $A = \begin{bmatrix} a & b \\ c & d \end{bmatrix}$

Then $A^2 = \begin{bmatrix} a^2+bc & ab+bd \\ ac + cd & bc + d^2 \end{bmatrix} = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$

Equating the entries, we have the following:

I: If both b=c=0, then $A=I$ or $A=-I$


III: if one of b,c $\neq$ 0, the $a = \pm \sqrt{1 - bc} = -d$. Note for $bc < 1$, a, dwill be imaginary and a= \$i\sqrt{bc-1}$ = -d

Therefore $A = \begin{bmatrix} \pm\sqrt{1-bc} & b \\ c & \mp\sqrt{1-bc} \end{bmatrix}$.   





---
**Symmetric and Skew-Symmetric Matrices**

$A$ is a symmetric matrix if $A^T = A$

if $A$ is symmetric and invertible, then  $A = LDU$ then $A^T = U^TDL^T = LDU$ and $L=U^T$ by uniques of factorization (see above). Therefore for symmetric matrices $A = LDL^T$

$A$ is skew symmetric if $A^T = -A$
Note that the diagonal values of a skew symmetric matrix are all zeros.

Example: $\begin{bmatrix} 0 & 3 & 2 \\ -3 & 0 & 1 \\ -2 & -1 & 0 \end{bmatrix}$

---
**Vector product**

In 3D, we are used to vectors represented as $\overrightarrow{v} = v_1 \overrightarrow{i} + v_2 \overrightarrow{j} + v_3 \overrightarrow{k}$ and $\overrightarrow{w} = w_1 \overrightarrow{i} + w_2\overrightarrow{j} + w_3 \overrightarrow{k}$

We have the notion of cross product of two vectors, which gives a third vector which is normal to both. Note that any  two vectors define a plane and the cross product is a vector normal to the plane.

The cross product is defined as $\overrightarrow{w} \times \overrightarrow{v} = (w_2v_3 - w_3v_2)\overrightarrow{i} + (w_3v_1 - w_1v_3) \overrightarrow{j} + (w_1v_2 - w_2v_1) \overrightarrow{k}$


We can calculate vector product through matrix vector multiplication, if we represent $\overrightarrow{w}$ as a skew symmetric matrix as: $[w]_\times = \begin{bmatrix} 0 & -w_3 & w_2 \\ w_3 & 0 & -w_1 \\ -w_2 & w_1 & 0 \end{bmatrix}$

Now $\omega \times v = [w]_\times v = \begin{bmatrix} 0 & -w_3 & w_2 \\ w_3 & 0 & -w_1 \\ -w_2 & w_1 & 0 \end{bmatrix} \begin{bmatrix} v_1 \\ v_2 \\ v_3 \end{bmatrix}$


---
**Q6 Vector product**

a) What is $v \cdot \omega \times v$

b) What is $\omega \times \omega$


c) What is the rank of $[\omega]_\times$ (*Hint*: You can guess from its operation of realizing the cross product)


Ans:

a) $v \cdotp \omega \times v = v^T [\omega]_\times v = 0$

as $\omega \times v$ give a vector perpedicular to the plane formed by $v$ and $\omega$

b) $\omega \times \omega = 0 $

c) Since $[\omega]_\times$ maps a vector $v$ to its cross product with $\omega$, any vector collinear with $\omega$ will map to $0$. Hence the $dim(NullSpace([\omega]_\times)) = 1$ and $rank([\omega]_\times) = 2$

---
**Matrix Product and Matrix Group**

Associativity: $A(BC) = (AB)C$ provided the multiplication is possible in terms of the matrix dimensions.

Not commutative: $AB \ne BA$ in general (even when A & B are square)

Consider the set of $nxn$ non-singular matrices $GL(n) = \{A \in ℜ^{nxn}\}$ along with the matrix product '·'. This is a "Group" and called the General linear group:

1. Closure under multipication: $A, B \in GL(n)$ then $A·B \in GL(n)$
2. Associative: $A, B, C \in GL(n)$ then $(A·B)·C = A·(B · C)$
3. Identity: $I_n \in GL(n)$ such that $A · I_n = I_n · A = A$
4. Inverse: $∀\ A \in GL(n)$ then $∃\ A^{-1}$ such that $A · A^{-1} =I_n = A^{-1}A$


---
**Q7**

Which of these matrix sets are groups under usual matrix multiplication and Inverse?

a) Set of symmetric matrices

b) Set of Positive Matrices (all entries are strictly greater than 0)

c) Set of diagonal invertible matrices

d) Set of permutation matrices (Permutation matrix has exactly single 1 in each row and column and zeros every where else)

Ans:

a) No. $A, B$ is symmetric, then $(AB)^T = BA \neq AB$ in general (you can construct examples for 2x2 symmetric matrices to check this) and is not within the set. Hence not closed and therefore not a group.

b) No. $I$ does not belong to this set

c) Yes. An invertible diagonal matrix has non-zero on diagonal and zero everywhere.  $I$ belongs to this set. Product of two invertible diagonal matrix is a diagonal matrix which is invertible

d) Yes. $I$ belongs to this set. Product of permutation matrix is also a permutation matrix hence closed.



---
**A Brief on Number Representations**

Floating point numbers are presented as below (https://en.wikipedia.org/wiki/Floating-point_arithmetic):

Type | Total Bits | sign | exponent | mantissa | bits of precision | exponent bias  | decimal digits(mantissa)
-----|------------|------|----------|----------|-------------------|----------|------------
Half Precision | 16 | 1 | 5 | 10 | 11 | 15 | ~3.3
Single Precision|32 | 1 | 8 | 23 | 24 |127 | ~7.2
Double Precision|64 | 1 | 11| 52 | 53 |1023|~15.9
Extended Precision (x86)|80| 1| 15| 64 | 64 |16383|~19.2

Lets take 16-bit numbers as an example.
the left most bit: is the sign bit.
Next 10 bits are the mantissa (or significand).
Last 5 bits are exponent.

Normalized numbers have a binarypoint after the first bit and the first bit is always 1. For example, a binary number 0.001x$2^0$ is represented as 1.000 x $2^{-3}$. That is, you left shift till the first non-zero bit comes to the first location (and corresponding adjust the exponent).

Since the first bit is '1' for a normalized representation, we dont need to store it. Hence we effectively have 10+1 = 11 bits of precision. Precision refers to the accuracy of representation. The gap between two numbers representatble by the mantissa is $2^{-10}$ and the round-off error is half of that and is $2^{-11}$

The exponent takes values from 00000 (0) to 11111 (31). All 1's is used to represent infitinity and NaN and all 0 for sub-normal numbers (where the first bit is not 1) Hence the exponent ranges from 1 to 30. With exponent bias of 15, the represented exponent is subtracted by the bias  to give the actual exponent. for example, an exponent if -11 is represented as -11+15 = 4. Hence the representable exponents range from -14 to 15 (30 values)


In [ ]:
print("float16 info:",np.finfo(np.float16) )

float16 info: Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------



**Round off errors**

Since the floating point representation can only represent finite numbers of values on the real line, there will be round off error of about $2^{-p}/2$.

As an example below, the real number 0.1 can only be represented within $0.02\%$ with 16-bit floating point numbers

In [ ]:
#declare a variable to be half precision floating point type and print its characteristics
f16 = np.float16("0.1")
f32 = np.float32("0.1")
f64 = np.float64("0.1")
print(f"Percentage error in value stored in f16={(f16-0.1)*100/0.1}%, and occupies {f16.itemsize} bytes")
print(f"Error in value stored in f32={(f32-0.1)*100/0.1}%, and occupies {f32.itemsize} bytes")
print(f"Error in value stored in f64={(f64-0.1)*100/0.1}%, and occupies {f64.itemsize} bytes")

Percentage error in value stored in f16=-0.02441406250000555%, and occupies 2 bytes
Error in value stored in f32=1.4901161138336505e-06%, and occupies 4 bytes
Error in value stored in f64=0.0%, and occupies 8 bytes


---
**Well Conditioned and Ill-Conditioned**

Ref: https://en.wikipedia.org/wiki/Condition_number

Regardless of the round off error, the nature of the matrix (or in general a function) will be such that it is very sensitive to inputs.

For example, in solving $Ax=b$, the input is $b$ and output $x$. Depending on the condition number of the matrix, a small perturbation of $b$ can lead to a large change in the solution $x$.

The example below illustrates this. We perturb $b$ to $d$ and $e$ and look at the changes in the soliutions.

The ratio of the relative change in output  (i.e. change in solution) to relative change in input  (change in b) ) is  equal to the condition number (kind of like an amplifier gain).


Too high a condition number means a ill-conditioned system. Any small errors in the input will through the solution off.

The condition number of a matrix is relted the ratio of its largest singular value to the smallest singular value (which in turn is related to the eigen values for a square matrix)

**Singular Value Decomposition**

Any matrix $A \in ℜ^{m \times n}$ can be decomposed as:

$A = U \Sigma V^T$

Where $U \in ℜ^{m \times m}$ and $V in ℜ^{n \times n}$ are orthogonal matrices, i.e.,  $U^TU=I$ and $V^TV=I$ and $\Sigma = [\sigma_{ij}]$ is a $m \times n$ diagonal matrix with non-negative values in the main diagonal ($\sigma_{ii} \geq 0$ and \sigma_{ij} = 0 $ for $i \neq j$ )

$\sigma_{ii}$ written simply as $\sigma_i$ are called the singular values.

For a matrix of rank $r$, there are exactly $r$ non-zero singular values.

$AV = U\Sigma$

$U^TA = \Sigma V$

The columns of $V$ and $U$ form the right-singular and left-singular verctors respectively.

If the singular values are usually arranged in a non-increasing order, i.e. $\Sigma=Diag(\sigma_1, \sigma_2, ..., \sigma_r,0,..)$ where $r$ is the rank of the matrix

Condition number of the matrix $κ(A) = \frac{\sigma_{max}}{\sigma_{min}}$

Note, the right nullspace of A is the set of columns of V with singular value 0

---
**Orthogonality**

Two vectors are orthogonal if their inner product (or dot product) is 0.

If $v_1, v_2, ... , v_k$ are pairwise orthogonal then they are linearly independent.

To see this, let $c_1 v_1 + c_2 v_2 + .... c_k v_k = 0$, then taking the dot product with $v_j$ on both sides gives $c_j v_j \cdotp v_j = 0$ and hence $c_j=0$ for all j.


*Orthogonality of Row space with NullSpace*

Let $A: V_n → W_m$ . Then

Null Space $N(A) = \{v \in V_n: Av = 0\} $

Row Space $R(A) = \{v \in V_n: s.t.\ \ v^T = w^T A, w \in W_m\}$

Then if $x \in R(A)$ then $x^T = u^TA$ for some $u \in W_m$
Let $y  \in N(A)$ then

$x^Ty = (u^TA)y = u^T(Ay) = 0$

Thus $R(A) \perp N(A)$ and each is called the orthogonal complement of the other.


Example:

$A = \begin{bmatrix} a \\ b \\ c \end{bmatrix}$ has rank 1, which is the rank of the $RowSpace(A)$.

$N(A) = \{\begin{bmatrix} x \\ y \\ z \end{bmatrix}\}$ such that $\begin{bmatrix} x & y & z \end{bmatrix}\begin{bmatrix} a \\ b \\ c \end{bmatrix} = ax + by +cz = 0\}$ is the orthogonal 2D plane.

In [ ]:
A = np.array([[1,1],[1,1.0001]],np.float32)
b = np.array([2,2],np.float32)
d = np.array([2.0,2.001],np.float32)
e = np.array([2.0,2.009],np.float32)

x = np.linalg.solve(A,b)
y = np.linalg.solve(A,d)
z = np.linalg.solve(A,e)

print(f"x={x}, y={y}, cond(A)={np.linalg.cond(A,p=2)}")
print(f"||b-d|| = {np.linalg.norm(b-d)}, ||x-y||={np.linalg.norm(x-y) }")
print(f"||b-e|| = {np.linalg.norm(b-e)}, ||x-z||={np.linalg.norm(x-z) }")

x=[2. 0.], y=[-7.9976163  9.997616 ], cond(A)=39995.3671875
||b-d|| = 0.0009999275207519531, ||x-y||=14.138764381408691
||b-e|| = 0.009000062942504883, ||x-z||=127.25898742675781


---
We know that column space of $A$ is $C(A) = \{w = Av\ \forall\ v \in V_n\}$

$dim(C(A)) = dim(R(A)) = rank(A)$

We can define left null space of $A$ as $LN(A) = \{w | w^TA = 0\}$

Note that $LN(A) \perp C(A)$

This leads to the nice diagram of the front cover of the Strang textbook.

Note that we can do a one-to-one map of $R(A)$ with $C(A)$ as:

$A:R(A) → C(A)$ with $x_r \in R(A)$ and $Ax_r = b \in C(A)$

This is a one-to-one mapping as otherwise if $Ax_r^{'} = b$, then $A(x_r^{'}-x_r) = 0$ and $x_r^{'}-x_r \in N(A)$.

However since $R(A)$ is a vector subspace, $x_r^{'}-x_r \in R(A)$ which can only happen if there difference is 0 and hence they are equal.



---
**Least Squares Solution**
Let $A:V_n → W_m$ and $rank(A) = k \leq min(m,n)$

Then $A^TA$ is a $nxn$ matrix and $AA^T$is a $mxm$ matrix, each with rank $k$.

Both are symmetric.

Lets assume that $m > n$ and $rank(A) = n$, that is more rows than columns.

Then $Ax =b $ need not have any solution as $b$ can be outside the the columns space of A (which has a dimension only $n$.

This is a common problem in many data fitting problems.

*Example*

Imagine that we have $m$ observations $\{(a_i,b_i\}$ and we want to fit a polynomial equation of degree $n-1$ to fit this. i.e

$y = \sum_{k=0}^{n-1}z_k x^k$

where we want to find the best estimates of the unknown parameters $\{z_k\}$

using the observed data, we can write $m$ simultaneous equations

$\sum_{k=0}^{n-1}z_k a_i^k = b_i$ one per observation $(a_i, b_i)$

this can be rewritten as a matrix equaiton:

$Az = b$ where $A$ is a $mxn$ matrix and

$A = \begin{bmatrix} 1 & a_1 & a_1^2 & ...& a_1^{n-1} \\ 1 & a_2 & a_2^2 & ... & a_2^{n-1} \\ ... \\ 1 & a_m & a_m^2 & ... & a_m^{n-1}\end{bmatrix}$ and $b=\begin{bmatrix} b_1 \\ b_2 \\ ... \\ b_m \end{bmatrix}$


**NOTE** the equations are linear in the unknowns and can be non-linear in the data terms.


---
**Geometric Solution to Least Squares**

We want to find $x^{'}$ such that error $e=b-Ax^{'}$ is minimum.

From geometry, we know that this happens when error is perpendicular to column space, i.e. $e \perp C(A)$. Hence $e \in LN(A)$ is in left nullspace of $A$.

Hence $A^Te = A^T(b-Ax^{'}) = 0$ which can be written as

$A^TAx^{'} = A^Tb$, also called as the **Normal** Equation


and hence $x^{'} = (A^TA)^{-1}A^Tb$ is the solution such that $Ax^{'} = A(A^TA)^{-1}A^Tb$ is closest to b.

Since we asumed rank(A) = n, rank($A^TA$) = n and it is invertible.





---
**Projection Matrix**

The matrix $P = A(A^TA)^{-1}A^T$ is called the projection matrix and it projects $b$ to $C(A)$

Note that $P^2 = P$ (check).

rank(P) = n


In general, if we are given $\{v_1, .... v_k\}$ and want to project another vector $w$ onto the Span($\{v_1, .... v_k\}$), we can form a matrix
$A = [v_1 v_2 ... v_k]$ and find the projection matrix $P=A(A^TA)^{-1}A^T$ and do $w_A=Pw$ to do the projection.

Hence, in general if $S \subset V$ a subspace and $P_S$ be the projection matrix that projects any vector onto the subspace, then

for any $v \in V$ we can write

$v_S = P_S v$ and $v_\perp = v - P_S v = (I - P_S)v$ with $v = v_S + v_\perp$

Therefore a reflection of a vector $v$ about a subspace can be written as:

$v_r = v_\perp - v_S = (I-2P_S)v$

Hence $H=I-2P_S$ is the reflection matrix about a subspace $S$. This is like a ray of light reflecting of the surface

Note -$-v_r$ is also another kind of reflection (mirror reflection)


---
**Optimization based derivation of least means square solution**

The residual error is $e = b-Ax$ and we would like to minimize its $L_2$ norm as:

$min_x ||e||^2$ where

$||e||^2 = e^Te  = (b-Ax)^T (b-Ax) = x^TA^TAx -b^TAx - x^TA^Tb + b^Tb$

Note that $b^TAx = x^TA^Tb$ as it is a scalar

We have $n$ elements in the variable $x$ and we should differentiate with resepect to each and put the derivative to 0.

This can be compactly done using vector differentiation or gradient as:

$\nabla L = 2A^TAx-2A^Tb = 0$ (at extrema. we have used L to represent the square error). The extrema point $x^{'} = (A^TA)^{-1}A^Tb$ same as derived via geometric consideration.

The equivalent for double derivative is called the Hessian and is $A^TA$ which is positive semi definite in general and positive definite for vectors not in the null space of A (equivalent to second derivative being positive) and hence the extrema is a minima.

A matrix $B$ is positive definite is $x^TBx > 0 $ for all $x \neq 0$.

Since $x^T(A^TA)x = (x^TA^T)(Ax) = ||Ax||^2$ it is positive definite. I.e. the shape of the loss function at this point is "upward facing parabola" as anydirection you move, will only increase L.


The benefit of this optimization approach is that we can add *regularization*, ie additional constraints on the parameters. for example we can look for parameters that are not too large in magnitude. i.e. $||x||^2$ is kept small. Or we might also bring in weights for different error terms via a diagonal weight matrix $e = W(b-Ax)$

So $L = e^Te + \lambda x^Tx$ is the loss function to be minimized and

$\nabla L = (A^TW^TWA+\lambda I)x^{'}-A^TW^TWb=0$ and hence

$x^{'} = (A^TW^TWA+\lambda I)^{-1}A^TW^TWb$

is the optimal solution


---
**Q7**

Find the weighted least squares solution to $A = \begin{bmatrix} 1 & 0 \\ 1 & 1 \\ 1 & 2 \end{bmatrix}$ $b = \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}$ and $W=\begin{bmatrix} 2 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{bmatrix}$

In [ ]:
#Ans

A = np.array([[1., 0],[1,1],[1,2]])
b = np.array([0,1,1])
W = np.array([[2,0,0],[0,1,0],[0,0,1]])

#Your Answer Here
x = np.linalg.inv(A.T @ W.T @ W @ A) @ A.T @ W.T @ W @ b
e = A@x - b
print(f"x={x}, Ax = {A@x},\n e = {e} and ||e||={np.sqrt(np.linalg.norm(e))}")

x=[0.04761905 0.57142857], Ax = [0.04761905 0.61904762 1.19047619],
 e = [ 0.04761905 -0.38095238  0.19047619] and ||e||=0.6546536707079771


---
**Q8**
If $V = Span(\{[1,1,0,1]^T, [0,0,1,0]^T\})$, find

a) a basis for orthogonal complement of $V$ which is $V^\perp$

b) The projection matrix $P$ onto V

c) The vector in $V$ closest to $b=[0,1,0,-1]$



Ans:

a)

Let $A = \begin{bmatrix} 1 & 0 \\ 1 & 0 \\ 0 & 1 \\ 1 & 0 \end{bmatrix}$

$V = C(A)$ column space of A.

$V^\perp$ is the left null space. Since rows 1,2, 4 identical, we can infer the basis vectors of the left null space as $\{[-1,0,0,1]^T,[0,-1,0,1]^T\}$

b) $P = A(A^TA)^{-1}A^T$

c) $Pb$

In [ ]:
#Ans contd.
A=np.array([[1,0],[1,0],[0,1],[1,0]])
b = np.array([0,1,0,-1])

#Your code here
P = A @ np.linalg.inv(A.T @ A) @ A.T
Pb = P @ b

print(f"P={P} and closest vector in V to b ={Pb}")

P=[[0.33333333 0.33333333 0.         0.33333333]
 [0.33333333 0.33333333 0.         0.33333333]
 [0.         0.         1.         0.        ]
 [0.33333333 0.33333333 0.         0.33333333]] and closest vector in V to b =[0. 0. 0. 0.]


---
**Q9**

Let $P$ Project onto Subspace $S$ and $Q$ project onto its orthogonal complement $S^\perp$.

a) What is $P+Q$

b) What is $PQ$

c) Show that $P-Q$ is its own inverse.

Ans:

a) let $x$ be any vector then $Px = x_s$ and $Qx=x_{s^\perp}$ and $x = x_s + x_{s^\perp}$

Therefore $(P+Q)x = Px + Qx = x$ and hence $P+Q=I$

b) $PQx = Px_{s^\perp} = 0$ therefore $PQ=0$. similarly $QP=0$

c) $(P-Q)(P-Q) = P^2 -PQ -QP - Q^2 = P + Q = I$
since for any projection matrix $P^2=P$

---
**Q10**

If $P=P^TP$ show that it is a projection matrix

Ans:

$P^T = (P^TP)^T = P^TP = P$ hence P is symmetric and $P^2 = P^TP = P$ which means it is a projection matrix.

---
**Q11**

Let $v_1 = [1,1,0]^T$ and $v_2=[1,1,1]$ be two vectors that span a plane.

a) Find the projection matrix $P$ that will project any vector onto that plane

b) Find a non-zero vector which projects to 0 when P is applied.

In [ ]:
#Ans

A = np.array([[1,1],[1,1],[0,1]])
P = A @ np.linalg.inv(A.T @ A ) @ A.T
b = np.cross([1,1,0], [1,1,1])
print(f"P={P} b={b}")

P=[[0.5 0.5 0. ]
 [0.5 0.5 0. ]
 [0.  0.  1. ]] b=[ 1 -1  0]


---
**QR Decomposition**

Any matrix $A$ which is $m \times n$ can be decomposed in to a product of a orthogonal matrix $Q$ which is $m \times m$ w and an upper triangular matrix $R =[r_{ij}]$ which is $m x n$ with $r_{ij}=0$ for $i \gt j$

$A = QR$

This is useful for least squares solution as the straightforward solution will need inverse of $A^TA$ which has a condition number of $\kappa(A)^2$

An alternative approach to solve $A^TAx = A^Tb$ is to use $A=QR$, where $Q$ is orthogonal.

Hence $||Ax-b||_2 = ||Q^TAx-Q^Tb||_2$ and hence solution of latter gives solution of former.

Simplifying further we get the solution of $min_x ||Ax-b|| = min_x ||Rx-Q^Tb||$

For the case $m > n$ and full column rank $A$ (i.e rank = n),

we can solve the above to obtain: $x_{ls} = R^{-1}Q^Tb$.

Note that the condition number of $R$ is same of that $A$ and hence is only $Κ(A)$ and hence offers better numerical stability.


*Orthogonal matrix preserves vector lenghts $(L_2)$ and angles*

$||Qx||^2 = x^TQ^TQx = x^Tx = ||x||^2$

$<Qx,Qy> = x^TQ^TQy = x^Ty = <x,y>$

Any matrix which preserves angles and lengths is orthogonal. (You can prove by considering its actions on unit orthogonal vectors)

Example:

$Q(\theta) = \begin{bmatrix} \cos \theta & -\sin \theta \\ \sin \theta & \cos \theta \end{bmatrix}$

rotates vectors in 2D counter clockwise by $\theta$

$Q^T = Q(-\theta) = Q^{-1}$ does a rotation clock wise

Example:

Permutation matrices also preserve lengths and are orthogonal matrices.


*Uniqueness of QR factorization**

Lets assume that $A$ is non-singular i.e. rank n.

Then $A=QR = QDDR$ where $D^2 = I$ the identity matrix. Each element of D is +1 or -1, hence in general $QR$ factorization is not unique. However if we insist on diagonals of $R$ be positive, then factorization is unique.

If $rank(A) = k < n$ then factorisation is not unique. Let first $k$ columns of $A$ be linearly independent, then $A = \begin{bmatrix}q_1 & q_2 &.. &q_k &q_{k+1} &.. &q_n\end{bmatrix} \begin{bmatrix} r_{11} &  r_{12} & ..& r_{1k}& r_{1{k+1}}& ..& r_{1n} \\ 0 & r_{21} & .. & r_{2k} & r_{2{k+1}} & .. & r_{2n} \\ ... \\ 0 & 0 & .. & r_{kk} & r_{k{k+1}} & .. & r_{kn} \\ 0 & 0 & .. & 0 & 0 & .. & 0 \\ ...\end{bmatrix}$ and $q_{k+1}, ... q_n$ can be any orthogonal basis of null space of $A$

---
**Q12**

If $u$ is a unit vector, then show that $Q=I-2uu^T$ is a orthogonal matrix. (it is infact the reflection about the vector $u$)



Ans:

$QQ^T = (I-2uu^T)(I-2uu^T) = I^2 +4(uu^T)(uu^T) -4uu^T $

The middle term with associativity is $4(uu^T)(uu^T) = 4u(u^Tu)u^T = 4uu^T$

hence the result follows.

---
**Q13**

Let $A = \begin{bmatrix} 1 & 1\\2 & -1 \\ -2 & 4\end{bmatrix}$ and $b=[1, 2, 7]^T$


a) find orthonormal $q_1, q_2, q_3$ such that the first two span the column space of $A$

b) Which fundamental subspace, defined by $A$, does $q_3$ belong to?

c) Use QR decomposition to solve $Ax=b$ with least squares solution

Ans:

a) $q_1, q_2$ obtained by code below. $q_3$ is orthogonal to them and so $q_3 = q_1 \times q_2$ (cross product

b) $q_3$ belongs to left nullspace of $A$

c) done in code below

In [ ]:
#Ans:

A = np.array([[1,1],[2,-1],[-2,4]])

Q,R = np.linalg.qr(A)

print(f"Q={Q},\n R={R}")

b = np.array([1,2,7])
c = Q.T @ b
x = np.linalg.inv(R) @ c
print(f"Solution x={x}")

Q=[[-0.33333333 -0.66666667]
 [-0.66666667 -0.33333333]
 [ 0.66666667 -0.66666667]],
 R=[[-3.  3.]
 [ 0. -3.]]
Solution x=[1. 2.]


---
**Householder tranformations to obtain QR decomposition**

(See chapter 5.1 of Golub's Matric Computations for a more extensive discussion)

We know that if $u$ is a vector than $H=I-2uu^T$ is a reflection matrix such that $Hv$ reflects $v$ about $u$ and $H$ is orthogonal.

So idea is to take $A$ and work column by column by multiplying with suitable $H_1, H_2,...$ such that it gets converted into $R$ which is upper triangular.

i.e. $H_{n-1} ... H_1 A = R$

Then $Q^T = H_{n-1} ... H_1$

Consider what matrix can reflect vector $x$ to $y$.

We can find $u = x-y$ and then $u_n = \frac{u}{||u||}$ is the unit normal then $H_u = I-2u_nu_n^T$ will move $x$ to $y$.

This idea is used step by step. Start with first column of $A = \begin{bmatrix} a_1 & a_2 & ... & a_n \end{bmatrix}$ which is  $a_1$. We want to move it to $\begin{bmatrix} ||a_1|| \\ 0 \\ ... \\0 \end{bmatrix}$ by finding the suitable householder transformation $H_1$, which we can find by the idea in previous para. (Note the reason for the choice of the first element is to preserve the length of $a_1$ as orthogonal matrices preserve that).

Thus, $u_1=a_1 - ||a_1|| [1, 0, 0...,0]^T$

and $H_1 = I-2u_1 u_1^T /||u_1||^2$

and so on.

A worked out example below will illustrate further.



---
**Example: Using Householder method for QR decomposition**


Let $A=\begin{bmatrix} 1 & 2 & 6 \\ 4 & 0 & 5 \\ 7 & 8 & 9 \end{bmatrix} = \begin{bmatrix} c_1 & c_2 & c_3 \end{bmatrix}$

The first column $c_1=\begin{bmatrix} 1 \\ 4 \\ 7 \end{bmatrix}$ has a magnitude $||c_1|| = 8.124$

In [ ]:
A = np.array([[1,2,6],
              [4,0,5],
              [7,8,9]])
c1 = A[:,0].reshape(3,1)
print(c1,np.linalg.norm(c1))

[[1]
 [4]
 [7]] 8.12403840463596


The first householder vector is $u_1=c_1 - ||c_1||\begin{bmatrix} 1 & 0 & 0 \end{bmatrix} = $

In [ ]:
u1 = (c1-np.linalg.norm(c1)*np.array([1,0,0]).reshape(3,1)).reshape(3,1)
print(u1, np.linalg.norm(u1))
print(u1@u1.T)

[[-7.1240384]
 [ 4.       ]
 [ 7.       ]] 10.758806773556634
[[ 50.75192319 -28.49615362 -49.86826883]
 [-28.49615362  16.          28.        ]
 [-49.86826883  28.          49.        ]]


The first householder matrix is:

$H_1 = I-2u_1 u_1^T / ||u_1||^2$

$A_1 = H_1 \times A$

In [ ]:
H1 = np.eye(3)-2*u1@u1.T/np.linalg.norm(u1)**2
A1 = H1@A
print(f"H1={H1}")
print(f"H1 x A={A1}" )

H1=[[ 0.12309149  0.49236596  0.86164044]
 [ 0.49236596  0.72354671 -0.48379326]
 [ 0.86164044 -0.48379326  0.1533618 ]]
H1 x A=[[ 8.12403840e+00  7.13930648e+00  1.09551427e+01]
 [ 8.32667268e-16 -2.88561413e+00  2.21779001e+00]
 [ 1.66533454e-15  2.95017527e+00  4.13113252e+00]]


---
Second householder matrix

Now rotate the column below the main diagonal to 0, while preserving length

$c_2 = A[1:-1,1]$ //second column from diagonal and below

$u_2 = c_2 - ||c_2||\begin{bmatrix} 1 \\ 0 \end{bmatrix}$

$G_2 = I_2 - 2 u_2 u_2^T / ||u_2||^2 $

$H_2 = \begin{bmatrix} 1 & \bf{0}  \\ \bf{0} & G_2 \end{bmatrix}$

In [ ]:
c2 = A1[1:,1].reshape(2,1)
print(c2)
u2 = c2-np.linalg.norm(c2)*np.array([1,0]).reshape(2,1)
print(u2, np.linalg.norm(u2))
G2 = np.eye(2)-2*u2@u2.T/np.linalg.norm(u2)**2
print(G2)
H2  = np.eye(3)
H2[1:,1:] = G2
print(H2)
A2=H2@A1
A2[A2<10e-14]=0
R=A2
Q=(H2@H1).T
print(f"R={A2} Q = {Q}")
print(f"Checking orthogonality of Q as:||I-Q Q^T||={np.linalg.norm(Q@Q.T-np.eye(3))}")
print(f"Check the different of Q@R with A as: ||QR-A||= {np.linalg.norm(Q@R-A)}")

[[-2.88561413]
 [ 2.95017527]]
[[-7.01239291]
 [ 2.95017527]] 7.607705853828992
[[-0.6992413   0.71488573]
 [ 0.71488573  0.6992413 ]]
[[ 1.          0.          0.        ]
 [ 0.         -0.6992413   0.71488573]
 [ 0.          0.71488573  0.6992413 ]]
R=[[ 8.1240384   7.13930648 10.9551427 ]
 [ 0.          4.12677877  1.40251734]
 [ 0.          0.          4.4741249 ]] Q = [[ 0.12309149  0.27169184  0.95447998]
 [ 0.49236596 -0.85179064  0.178965  ]
 [ 0.86164044  0.44792439 -0.23861999]]
Checking orthogonality of Q as:||I-Q Q^T||=9.883854019163205e-16
Check the different of Q@R with A as: ||QR-A||= 5.468732061277671e-15


---
**Gram-Schmidt and QR decomposition**

Let $A = [a_1, a_2, ..., a_n]$ be a mxn matrix

Then Gram-Schmidt procedure for orthogonalization is:

$b_1 = a_1$ and $q_1 = \frac{1}{||b_1||} b_1$

$b_2 = a_2 - <a_2, q_1>q_1$ and $q_2 = \frac{1}{||b_2||} b_2$

$b_3 = a_3 - <a_3, q_2>q_2 -<a_3, q_1>q_1$ and $q_3 = \frac{1}{||b_3||} b_3$

and so on.

We can rearrange and write:

$A = [a_1, a_2, ..., a_n] = [q_1, q_2,  ... q_n]\begin{bmatrix} q_1^Ta_1 & q_1^Ta_2 & ... & q_n^Ta_n \\ 0 & q_2^Ta_2 & ... & q_n^Ta_n \\ ... \\ 0 & 0 & ... & q_n^Ta_n \end{bmatrix} = QR$

$Q$ has orthonormal columns and if $m = n$, Q is an orthogonal matrix.

Solving least squares becomes easy as ⁉

$Ax^{'} = QRx^{'} = b$ and $Rx^{'} = Q^Tb$ can be solved by backward substitution








---
**Example: We will use Gram-Schmidt for QR decomposition**

In [ ]:
A = np.array([[1,2,6],
              [4,0,5],
              [7,8,9]])

Q=np.zeros((3,3))
R=np.zeros((3,3))

#step 1
b = A[:,0]
Q[:,0] = b/np.linalg.norm(b)
R[0,0] = np.linalg.norm(b)

#step 2
b = (A[:,1]-(A[:,1].T@Q[:,0])*Q[:,0])
Q[:,1] = b/np.linalg.norm(b)

print(Q[:,0].T @ Q[:,1])

R[0,1] = Q[:,0].T@A[:,1]
R[1,1] = np.linalg.norm(b)

#step 3
b = (A[:,2]-(A[:,2].T@Q[:,0])*Q[:,0]-(A[:,2]@Q[:,1])*Q[:,1])
Q[:,2] = b/np.linalg.norm(b)

R[0,2] = Q[:,0].T@A[:,2]
R[1,2] = Q[:,1].T@A[:,2]
R[2,2] = np.linalg.norm(b)

print(Q)
print(R)

print(f"||QxQ^T-I||={np.linalg.norm(Q@Q.T-np.eye(3))}")

print(f"||QR-A||={np.linalg.norm(Q@R-A)}")

1.6653345369377348e-16
[[ 0.12309149  0.27169184  0.95447998]
 [ 0.49236596 -0.85179064  0.178965  ]
 [ 0.86164044  0.44792439 -0.23861999]]
[[ 8.1240384   7.13930648 10.9551427 ]
 [ 0.          4.12677877  1.40251734]
 [ 0.          0.          4.4741249 ]]
||QxQ^T-I||=7.986715129536681e-16
||QR-A||=9.057664235374552e-16
