<a href="https://colab.research.google.com/github/AshrithSagar/CP220-M4RAS-2024/blob/main/CP220_2024_Quiz1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
**CP220-2023 Midterm**

Answers

---
**Q1**
Consider the following sets:

1. $S_a = \{f:ℝ → ℝ| f$ has finitely many zeros $\}$

2. $S_b = \{f:ℝ → ℝ | f$ is monotonous non-decreasing $\}$

3. $S_c = \{f:ℝ→ℝ| f$ is a polynomial of finite degree $\}$

Which of the following statements are true:

a) All are vector spaces

b) Only $S_c$ is a vector space and $S_a$, $S_b$ arent.

c) $S_c$ and $S_a$ are vector spaces

d) $S_a$ and $S_b$ are vector spaces


Ans:

b)

As $S_a$ doesnt contain the $0$ function and $S_b$ is not closed under scalar multiplication with negative scalars

---
**Q2**

Let

$u_1 = \begin{bmatrix}2 \\ 3 \\ -1 \end{bmatrix}$,

$u_2 = \begin{bmatrix}6 \\ 1 \\ 0 \end{bmatrix}$,

$u_3 = \begin{bmatrix}-6 \\ 7 \\ -3 \end{bmatrix}$

and $H=SPAN(u_1, u_2, u_3)$

Which of the following are true:

a) $u_1, u_2, u_3$ are the basis vectors of H

b) $u_1, u_2$ are the basis vectors of H

c) $u_2, u_3$ are the basis vectors of H

d) $u_1, u_3$ are the basis vectors of H

In [ ]:
import numpy as np


Ans:
b,c,d

$3u_1 - 2u_2 -u_3=0$ hence $u_1, u_2, u_3$ are linearly dependent and  only 2 out of these 3 are linearly independent and form the basis.

In [ ]:


A = np.array([[2,6,-6],[3,1,7],[-1,0,-3]])

u,s,v=np.linalg.svd(A)
print(v)
s=s[s>1e-16]
print(f"singular values:{s}")
x = np.array([3, -2, -1])
print(A@x)

[[-0.05953099  0.37355202 -0.92569701]
 [ 0.59464184  0.75811912  0.26768728]
 [ 0.80178373 -0.53452248 -0.26726124]]
singular values:[10.31863629  6.20691107]
[0 0 0]


---
**Q3**

Let $A=\begin{bmatrix} 1 & -4 \\ 2 & -8 \\ -1 & 4 \end{bmatrix}$

Which of the following statements are correct:

a) Row space has dimension 1

b) Right Null space of $A$ has the basis set $\{\begin{bmatrix} 1 \\ 2 \\ -1 \end{bmatrix}\}$

c) Left Null space has dimension 2

d) Left null space has dimension 1

Ans:

$A$ has rank 1. Hence

a), c) are correct.

---
**Q4**

Which of the following are True:

a) If columns 1 & 3 of B are same, then so are columns 1 & 3 of AB

b) If rows 1 & 3 of B are same, so are rows 1 & 3 of AB

c) if rows 1 & 3 of A are same, then so are rows 1 & 3 of AB

d) $(AB)^2 = A^2B^2$



Ans:

If $B=[b_1\ b_2\ b_3\ ...]$ then $AB=[Ab_1\ Ab_2\ Ab_3\ ...]$

If $A=\begin{bmatrix} a_1 \\ a_2 \\ a_3 \\ ... \end{bmatrix}$ then $AB=\begin{bmatrix} a_1B \\ a_2B \\a_3B \\ ... \end{bmatrix}$

Hence a) and c) are true


---
**Q5**

Which of the following are guaranteed to be equal to $(A+B)^2$

a) $A^2 + 2AB + B^2$

b) $A(A+B) + B(A+B)$

c) $(A+B)(B+A)$

d) $A^2+AB+BA+B^2$

Ans:
b, c, d

---
**Q6**

If A is 3x5, B is 5x3, C is 5x1 and D is 3x1, which of the following matrix operations are allowed

a) BA

b) AB

c) ABD

d) A(B+C)

Ans:
a), b), c)

---
**Q7**

Which of the following are True

a) if $A^2$ is defined, then A is necessarily square

b) if AB and BA are defined, then A & B are square

c) if AB and BA are defined, then AB and BA are square

d) If AB = B then A = I

Ans:

a), c)

In case of d), we can only say that the columns of B are from the eigenspace of A corresponding to eigen value 1.

---
**Q8**

Which of the following are true

a) If $L_1U_1 = L_2U_2$ with $L_1, L_2$ lower triangular with diagonal entries as 1 and $U_1, U_2$ with upper triangular with diagonal non-zero, then this LU factorization is unique (i.e. $L_1 = L_2$ and $U_1 = U_2$

b) if $A^2 + A = I$ then $A^{-1} = A + I$

c) If all diagonal entries of A are zero, then A is singular

Ans:

a), b)

For c) an example: $A=\begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}$ is non-singular

---
**Q9**

Let $A=\begin{bmatrix} 1 & 1 \\ 0 & 2 \end{bmatrix}$

The singular values of $A$ in decreasing order are:




Ans:

$\sqrt{3+\sqrt{5}}$, $\sqrt{3-\sqrt{5}}$

In [ ]:
A = np.array([[1,1],
              [0,2]])
_,s,_ = np.linalg.svd(A)
print(s, np.sqrt(3+np.sqrt(5)), np.sqrt(3-np.sqrt(5)))

[2.28824561 0.87403205] 2.288245611270737 0.8740320488976421


**Q10**

Let $A=\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 1 &
 1 & 0 \end{bmatrix}$.

and $b=\begin{bmatrix} 2 \\ 2 \\ 2 \end{bmatrix}$

Then if $x_s = min_x ||Ax-b||$, the number of solutions which achieve minima is and the minimim norm solution is

In [ ]:
A = np.array([
    [1,0,1],
    [0,1,1],
    [0,0,0]
])

Q,R = np.linalg.qr(A)
print(Q)
print(R)

b = np.array([2,2,2]).reshape(3,1)
x = np.linalg.inv(R[:2,:2])@Q[:2,:2].T@b[:2]
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 0.]]
[[2.]
 [2.]]
