<a href="https://colab.research.google.com/github/AshrithSagar/CP220-M4RAS-2024/blob/main/CP220_2024_Quiz2_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
**CP220-2024 Quiz2**

Copy this notebook into your directory

Please write the final answer using the form

Also paste the link to your answer notebook using the same form

The text cells for answers are optional - but might be useful for you to work through your solution

(you can also write on paper and take a photo and upload your work)

This could be useful in case there is a case for partial grading.

The code cells are also optional but higly recommended as it will allow you to calculate the answers easily.

In [ ]:
import numpy as np

---
**Q1 (1pt)** <br>

Let $A=\begin{bmatrix} 1 & 1 \\ 0 & 2 \end{bmatrix}$

The singular values of $A$ in decreasing order are (include only one digit after decimal point):




In [ ]:
#Ans
A = np.array([[1,1],
              [0,2]])
_,s,_ = np.linalg.svd(A)
print("%.1f, %.1f" % (s[0],s[1]))

2.3, 0.9


---

**Q2 (2pt)**

Consider a unit square (vertices at (0.5,-0.5), (0.5,0.5),(-0.5,0.5), (-0.5,-0.5))

It undergoes an arbitrary rotation and  the vertices end up as

B = np.array(
    [[-0.18,0.68,0.18,0.18],
 [-0.68,-0.18,0.68,0.68]]
)

Let R be the rotation matrix which results in this rotation.

Then the elements of R[0,0], R[0,1], R[1,0], R[1,1] with upto 1 decimal precision after are:



---

Ans:

From Wahba's algorithm

Let $BA^T = U\Sigma V^T$

Then the optimal $R = UV^T$

In [ ]:
A = np.array([[0.5,-0.5],[0.5,0.5],[-0.5,0.5],[-0.5,0.5]]).T
Ra = np.array([[np.cos(np.pi/3), np.sin(np.pi/3)],[-np.sin(np.pi/3),np.cos(np.pi/3)]])

#B = Ra@A

B = np.array(
    [[-0.18,0.68,0.18,0.18],
 [-0.68,-0.18,0.68,0.68]]
)

print (B)

U,S,Vh = np.linalg.svd(B@A.T)

R = U@Vh

print("R[0,0]=%.1f, R[0,1]=%.1f, R[1,0]=%.1f, R[1,1]=%.1f" % (R[0,0], R[0,1],R[1,0],R[1,1]))

print(np.linalg.norm(Ra-R))

[[-0.18  0.68  0.18  0.18]
 [-0.68 -0.18  0.68  0.68]]
R[0,0]=0.5, R[0,1]=0.9, R[1,0]=-0.9, R[1,1]=0.5
0.0042829382473276376


---
**Q3(2pt)**

Find the geometric multiplicity for the eigen value of 3 for a matrix under the following conditions:

a)  $A$ is  similar to  $\begin{bmatrix} 3 & 0 & 0 &0 \\ 0 & 3 & 1 & 0  \\ 0 & 0 & 3 & 1 \\ 0 & 0 & 0 & 3 \end{bmatrix}$

b)  $A$ is  similar to  $\begin{bmatrix} 3 & 1 & 0 &0 \\ 0 & 3 & 1 & 0  \\ 0 & 0 & 3 & 1 \\ 0 & 0 & 0 & 3 \end{bmatrix}$

c)  $A$ is  similar to  $\begin{bmatrix} 3 & 1 & 0 &0 \\ 0 & 3 & 0 & 0  \\ 0 & 0 & 3 & 1 \\ 0 & 0 & 0 & 3 \end{bmatrix}$

d)  $A$ is  similar to  $\begin{bmatrix} 3 & 0 & 0 &0 \\ 0 & 3 & 0 & 0  \\ 0 & 0 & 3 & 1 \\ 0 & 0 & 0 & 3 \end{bmatrix}$


---

Ans:

You can determine the geometric multiplicity (which is the dimension of the eigen subspace), by looking at the dimension of the kernel of $A-3I$, which can be obtained via SVD (and the number of times 0 singular value repeats).

a) 2

b) 1

c) 2

d) 3

In [ ]:

#a)
A = np.array([[0,0,0,0],[0,0,1,0],[0,0,0,1],[0,0,0,0]])
_,S,_ = np.linalg.svd(A)
print(S)


#b
A = np.array([[0,1,0,0],[0,0,1,0],[0,0,0,1],[0,0,0,0]])
_,S,_ = np.linalg.svd(A)
print(S)

#c
A = np.array([[0,1,0,0],[0,0,0,0],[0,0,0,1],[0,0,0,0]])
_,S,_ = np.linalg.svd(A)
print(S)

#d
A = np.array([[0,0,0,0],[0,0,0,0],[0,0,0,1],[0,0,0,0]])
_,S,_ = np.linalg.svd(A)
print(S)

[1. 1. 0. 0.]
[1. 1. 1. 0.]
[1. 1. 0. 0.]
[1. 0. 0. 0.]


---
**Q4 (1.5 pts)**

*Google's page rank algorithm*

Let pages 1, 2, 3 be three web pages, with an outgoing hyperlink from page 1 to page 2, and page 2 to page 3 and and one link each to pages 1 and 2 from page 3. We can model this connectivity as a graph G of Vertices (V) and Edges (E) as follows:

$V = \{ 1, 2, 3\}$

$E \in V \times V = \{(1,2), (2,3), (3,1), (3,2)\}$

The ajacency matrix representation of this graph is:

$A = \begin{bmatrix} 0 & 0 & 1\\ 1 & 0 & 1 \\ 0 & 1 & 0 \end{bmatrix}$

with the interpretation that rows and columns correspond to vertices 1,2,3 and $a_{ij}=1$ if there is an edge from node $j$ to node $i$ (i.e $(j,i) \in E$)


The weight of each outgoing edge from a vertex is just the 1 over the total number of outgoing edges from that vertex.

$W_{ik} = \frac{1}{\sum_{k=1}^{k=3} I((k,i)\in E)}$

Here $I(cond) = 1$ if and only if $cond$ is True, otherwise it is 0.

The weight adjacency matrix for the above web of pages can then be written as:

$G=\begin{bmatrix} 0 & 0 & 1/2 \\ 1 & 0 & 1/2 \\ 0 & 1 & 0 \end{bmatrix}$ (i.e. columns are normalized to sum to 1)

A person browsing the web, and looking at page $i$, will go out with equal chance through one of the hyperlinks of the page. For example, a person on web page 3, at the next time step, could land up in pages 1 and 2 with equal chance. Similarly, a person on web page 1, will go to page 2 and a person on page 2, will go to page 3.

Let the initial chances of being in pages 1, 2, 3 be $\pi_0 = \begin{bmatrix} \frac{1}{4} \\ \frac{1}{4} \\ \frac{1}{2} \end{bmatrix}$,

if $\pi_t$ is the vector indicating the probabilities of being in different pages at time $t$ then the same at $t+1$ is:

$\pi_{t+1} = G \pi_t$

Given the initial vector $\pi_0$ as above, what is $\pi_∞$? (write answer in decmial notation with 1 digit precision after decimal point and first component being positive)


(As an side, the values of $\pi_∞$ give the page rank of web pages, which is then used to sort the pages and present to you on a web search)

Ans:

Note that $\pi_n = G^n \pi_0$

Let $e_0, e_1, e_2$ be the eigen values of $G$ and lets write $\pi_0=c_0e_0 + c_1e_1 + c_2e_2$ as a linear combination of these.

Then $\pi_n = c_0\lambda_0^ne_0 +c_1\lambda_1^ne_1 + c_2\lambda_2^ne_2$


The characteristic equation of $G$ is $|G-\lambda I| =0$ giving:

$(\lambda-1)(\lambda^2+\lambda+1/2)=0$

The eigen values of $G$ are then 1, $\frac{-1 \pm i}{2}$.

Since the two complex conjugate eigen values have real part < 1, there power goes to 0 and only the eigen vector corresponding to eigen value 1 survives.

The  eigen vector corresponding to eigen value 1 is (with first element positive and entries summing to 1)

Hence $\pi_∞ = \begin{bmatrix} \frac{1}{5} \\ \frac{2}{5} \\ \frac{2}{5}\end{bmatrix}$

In [ ]:
G = np.array([[0,0,0.5],[1,0,0.5],[0,1,0]])
e,v = np.linalg.eig(G)
print("eigen values: ",e)
print("eigen vectors: ",v)
print(np.linalg.norm(v[:,2]))

eigen values:  [-0.5+0.5j -0.5-0.5j  1. +0.j ]
eigen vectors:  [[ 0.35355339+0.35355339j  0.35355339-0.35355339j  0.33333333+0.j        ]
 [ 0.35355339-0.35355339j  0.35355339+0.35355339j  0.66666667+0.j        ]
 [-0.70710678+0.j         -0.70710678-0.j          0.66666667+0.j        ]]
1.0


**Q5 (3.5pt)**

Let $A=\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 1 &
 1 & 0 \end{bmatrix}$.

and $b=\begin{bmatrix} 2 \\ 2 \\ 2 \end{bmatrix}$

Then if $x_s = min_x ||Ax-b||$,
the number of solutions which achieve minima is ________<br>
and the minimim norm solution is: [\__,\__,\__]

---

Ans:

Let $L = ||Ax-b||^2 = x^TA^TAx-2X^TA^Tb+b^Tb$

Then $∇L = 2A^TAx-2A^Tb =0$ for extrema

and Hessian is $A^TA$ is positive definite and hence it is a minima

Let SVD of A be $A=U\Sigma V^T$ and let rank of A be $r$ hence

$A = U[:,:r]\Sigma[:r,:r]V^T[:r,:]$

For brevity  - we will denote

$U_r = U[:,:r]$ -- the first r columns

$V_r = V[:,:r]$ -- the first r columns

$\Sigma_r = \Sigma[:r,:r]$ -- diagonal of r non-zero values

Then plugging this in the above equation

$A^TAx = V_r\Sigma^2_rV_r^Tx = V_r\Sigma_r U_r^Tb$

Multiplying by $V^T_r$ on both sides

$I_r \Sigma^2_r V_r^Tx = I_r\Sigma_rU^T_rb$

Where $I_r$ is a $r\times r$ identity matrix

Since $\Sigma_r$ is a diagonal of $r$ non-zero values (as A has rank r), then

$V_r^Tx  = \Sigma^{-1}_r U^T_r b$

$\hat{x} = V_r\Sigma_r^{-1}U^T_rb$ solves this equation.

In fact any $x=\hat{x}+\Sigma_{k={r+1}}^n \alpha_k v_k$ also gives the same residual error of ||Ax-b||

where $\{v_k| k=r+1, r+2,...,n\}$ are the right singular vectors corresponding to the 0 singular value (and form the null space of the kernel of A).

Thus $\hat{x}\ $ is the minimum norm solution.

In [ ]:
A = np.array([
    [1,1,0],
    [0,1,1],
    [1,2,1]
])


U,S,Vh = np.linalg.svd(A)

print("||A-U@diag(S)@Vh||=",np.linalg.norm(A-U@np.diag(S)@Vh))
print("||A.T@A  - Vh.T@diag(S**2)@Vh||=",np.linalg.norm(A.T@A-Vh.T@np.diag(S**2)@Vh))

Ur = U[:,:2]
Vr = Vh[:2,:].T
Sr = S[:2]

b = np.array([2,2,2]).reshape(3,1)
x = Vh[:2,:].T@np.diag([1/S[0],1/S[1]])@U[:,:2].T@b

print("x[0]=%.2f x[1]=%.2f x[2]=%.2f ||x||=%.2f" % (x[0,0],x[1,0],x[2,0],np.linalg.norm(x)))

print(f"Err={np.linalg.norm(A@x-b)}")


||A-U@diag(S)@Vh||= 1.7445949751796275e-15
||A.T@A  - Vh.T@diag(S**2)@Vh||= 8.144830983416995e-15
x[0]=0.44 x[1]=0.89 x[2]=0.44 ||x||=1.09
Err=1.1547005383792517


In [ ]:
# With the other matrix:
print("Using the matrix in the text cell:")
A = np.array([
    [1,0,0],
    [0,1,0],
    [1,1,0]
])
b = np.array([2,2,2])

#Approach 1
U,S,Vh = np.linalg.svd(A)

print("||A-U@diag(S)@Vh||=",np.linalg.norm(A-U@np.diag(S)@Vh))
print("||A.T@A  - Vh.T@diag(S**2)@Vh||=",np.linalg.norm(A.T@A-Vh.T@np.diag(S**2)@Vh))

Ur = U[:,:2]
Vr = Vh[:2,:].T
Sr = S[:2]

b = np.array([2,2,2]).reshape(3,1)
x = Vh[:2,:].T@np.diag([1/S[0],1/S[1]])@U[:,:2].T@b

print("Approach 1")
print("x[0]=%.2f x[1]=%.2f x[2]=%.2f ||x||=%.2f" % (x[0,0],x[1,0],x[2,0],np.linalg.norm(x)))
print(f"Err={np.linalg.norm(A@x-b)}")

print("Approach 2")
x, _, _, _ = np.linalg.lstsq(A, b, rcond=None)
print(f"x={x},||x||={np.linalg.norm(x)}, err={np.linalg.norm(A@x-b)}")

Using the matrix in the text cell:
||A-U@diag(S)@Vh||= 7.630168495706461e-16
||A.T@A  - Vh.T@diag(S**2)@Vh||= 1.0295784775289034e-15
Approach 1
x[0]=1.33 x[1]=1.33 x[2]=0.00 ||x||=1.89
Err=1.1547005383792517
Approach 2
x=[[1.33333333]
 [1.33333333]
 [0.        ]],||x||=1.8856180831641267, err=1.1547005383792517


---
**Q6 (1.5pts)**

Let $F$ be a subspace spanned by $\{\begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}\}$.

Let $G$ be a subspace spanned by $\{\begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 0 \\ 2 \end{bmatrix}\}$

The unit vector in G which is orthogoal  to F is given by: _______


---
Ans

Let $F = \begin{bmatrix} f_1 & f_2 \end{bmatrix}$

Let SVD of $F$ be $F = U_F \Sigma_F V_F^T$

Then $U_F$ is the orthonormal basis  for column space of $F$

Then the projection matrix onto the column space of F (i.e. the subspace spanned by columns of $U_F$) is $P_U = U_F U_F^T$

Hence the orthogonal complement of column space of G with respect to F is

$G_\perp = G - U_F U_F^T G$

Note that $F$ has rank 2, $G$ has rank 3 and $G_\perp$ has rank 1

Take SVD of $G_\perp$ and  the left singular vector corresponding to non-zero singular value is the unit vector orthogonal to column space of $F$

$G_\perp = U_\perp \Sigma_\perp V^T_\perp$

$U_\perp[:,0]$ gives the answer


In [ ]:
F = np.array([[1,0,0],[0,1,0],[1,1,0]])
G = np.array([[1,0,0],[0,1,0],[0,0,2]])
Uf,Sf,_ = np.linalg.svd(F)
print("singular values of F: ",Sf)
Fu = Uf[:,:2] #use only the left singular vector for non-zero singular values
G_p = (np.eye(3)-Fu@Fu.T)@G
Ugp,Sgp,_ = np.linalg.svd(G_p)
print("singular values of G perp to F: ",Sgp)
print("Unit vector in G perp F: %.1f %.1f %.1f" % (Ugp[0,0],Ugp[1,0],Ugp[2,0]))
print("check orthogonality of this w.r.t F",Ugp[:,0].T@F)

singular values of F:  [1.73205081 1.         0.        ]
singular values of G perp to F:  [1.41421356e+00 5.34834094e-16 4.23387726e-16]
Unit vector in G perp F: -0.6 -0.6 0.6
check orthogonality of this w.r.t F [-2.22044605e-16  1.11022302e-16  0.00000000e+00]
